import { QuizEntity } from "@/features/quiz/model/QuizModel";

export const general: QuizEntity = {
  name: "general",
  img: "/general.webp",
  words:
    [
      // phrases
      ["bonjour", "good morning"],
      ["salut", "hello"],
      ["bonne nuit", "good night"],
      ["enchanté", "nice to meet you"],
      ["s'il vous plait", "please"],
      ["merci", "thank you"],
      ["beacoup", "a lot"],
      ["à bientôt", "see you later"],
      ["de rien", "you are welcome"],

      // verbs
      ["être", "to be"],
      ["aller", "go"],
      ["avoir", "have"],
      ["devoir", "have to"],
      ["travailler", "work"],
      ["apprendre", "learn"],
      ["étudier", "study"],
      ["comprendre", "understand"],
      ["lire", "read"],
      ["écrire", "write"],
      ["écouter", "listen"],
      ["voir", "see"],
      ["trouver", "find"],
      ["marcher", "walk"],
      ["manger", "eat"],
      ["boire", "drink"],
      ["parler", "speak"],
      ["partir", "leave"],
      ["rester", "stay"],
      ["attendre", "wait"],
      ["prendre", "take"],
      ["acheter", "buy"],
      ["vendre", "sell"],
      ["habiter", "live"],
      ["nager", "swim"],
      ["chanter", "sing"],

      // food
      ["une pomme", "an apple"],
      ["une banane", "a banana"],
      ["une pêche", "a peach"],
      ["une orange", "an orange"],
      ["une pomme de terre", "a potato"],
      ["une tomate", "a tomato"],
      ["un concombre", "a cucumber"],
      ["une laitue", "a lettuce"],
      ["une aubergine", "an eggplant"],
      ["une betterave", "a beetroot"],
      ["une carotte", "a carrot"],
      ["un chou", "an cabbage"],
      ["une bouchée", "a snack"],
      ["un œuf", "an egg"],
      ["un sucre", "a sugar"],
      ["un sel", "a salt"],
      ["une eau", "a water"],
      ["un lait", "a milk"],
      ["un café", "a coffee"],
      ["un thé", "a tea"],

      // animals
      ["un chat", "a cat"],
      ["un chien", "a dog"],
      ["un cheval", "a horse"],
      ["une vache", "a cow"],
      ["un poulet", "a chicken"],
      ["un/une cochon", "a pig"],
      ["un guépard", "a cheetah"],
      ["une girafe", "a giraffe"],
      ["un éléphant", "an elephant"],
      ["un serpent", "a snake"],
      ["une araignée", "a spider"],
      ["une mouche", "a fly"],
      ["un moustique", "a mosquito"],

      // people
      ["un garçon", "a boy"],
      ["un homme", "a man"],
      ["un père", "a father"],
      ["un fils", "a son"],
      ["un monsieur", "sir"],
      ["une femme", "a woman"],
      ["une mère", "a mother"],
      ["une fille", "a girl"],
      ["une fils", "a daughter"],
      ["un enfant", "a child"],
      ["un étudiant", "a student"],
      ["un professeur", "a teacher"],
      ["un policier", "a policeman"],
      ["un pompier", "a fireman"],

      // home
      ["chez", "at home"],
      ["un tableau", "a table"],
      ["un placard", "a cupboard"],
      ["une chaise", "a chair"],
      ["une chambre", "a room"],
      ["une salle", "a room"],
      ["un canapé", "a sofa"],
      ["un ordinateur", "a computer"],
      ["un téléphone", "a phone"],


      // places
      ["une maison", "a house"],
      ["un immeuble", "a building"],
      ["devant", "in front"],
      ["derrière", "behind"],
      ["un lieu", "a place"],
      ["un pont", "a bridge"],
      ["un musée", "a museum"],
      ["un supermarché", "a supermarket"],
      ["une banque", "a bank"],

      // numbers
      ["une", "one"],
      ["un", "one"],
      ["deux", "two"],
      ["trois", "three"],
      ["quatre", "four"],
      ["cinq", "five"],
      ["six", "six"],
      ["sept", "seven"],
      ["huit", "eight"],
      ["neuf", "nine"],
      ["dix", "ten"],
      ["onze", "eleven"],
      ["douze", "twelve"],
      ["treize", "thirteen"],
      ["quatorze", "fourteen"],
      ["quinze", "fifteen"],
      ["seize", "sixteen"],
      ["dix-sept", "seventeen"],
      ["dix-huit", "eighteen"],
      ["dix-neuf", "nineteen"],
      ["vingt", "twenty"],
      ["cent", "hundred"],
      ["mille", "thousand"],
      //
      ["premier", "first"],
      ["deuxième", "second"],
      ["troisième", "third"],
      ["quatrième", "fourth"],
      ["cinquième", "fifth"],

      // dates
      ["lundi", "monday"],
      ["mardi", "tuesday"],
      ["mercredi", "wednesday"],
      ["jeudi", "thursday"],
      ["vendredi", "friday"],
      ["samedi", "saturday"],
      ["dimanche", "sunday"],

      ["hier", "yesterday"],
      ["aujourd'hui", "today"],
      ["demain", "tomorrow"],

      ["janvier", "january"],
      ["février", "february"],
      ["mars", "march"],
      ["avril", "april"],
      ["peut", "may"],
      ["juin", "june"],
      ["juillet", "july"],
      ["août", "august"],
      ["septembre", "september"],
      ["octobre", "october"],
      ["novembre", "november"],
      ["décembre", "december"],

      ["an", "year"]
    ]
};